platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/autolink-ios'

target 'example' do
	use_react_native!(path: "../node_modules/react-native")

	pod 'react-native-gles', :path => '../../react-native-gles.podspec'

	target 'exampleTests' do
		inherit! :search_paths
	end
end
