platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'example' do
	rn_path = '../node_modules/react-native'

  pod 'React', :path => "#{rn_path}"
	pod 'React-ART', :path => "#{rn_path}/Libraries/ART"
	pod 'React-Core', :path => "#{rn_path}/React"
	pod 'React-DevSupport', :path => "#{rn_path}/React"
	pod 'React-RCTActionSheet', :path => "#{rn_path}/Libraries/ActionSheetIOS"
	pod 'React-RCTAnimation', :path => "#{rn_path}/Libraries/NativeAnimation"
	pod 'React-RCTBlob', :path => "#{rn_path}/Libraries/Blob"
	pod 'React-RCTImage', :path => "#{rn_path}/Libraries/Image"
	pod 'React-RCTLinking', :path => "#{rn_path}/Libraries/LinkingIOS"
	pod 'React-RCTNetwork', :path => "#{rn_path}/Libraries/Network"
	pod 'React-RCTSettings', :path => "#{rn_path}/Libraries/Settings"
	pod 'React-RCTText', :path => "#{rn_path}/Libraries/Text"
	pod 'React-RCTVibration', :path => "#{rn_path}/Libraries/Vibration"
	pod 'React-RCTWebSocket', :path => "#{rn_path}/Libraries/WebSocket"

	pod 'React-cxxreact', :path => "#{rn_path}/ReactCommon/cxxreact"
	pod 'React-jsi', :path => "#{rn_path}/ReactCommon/jsi"
	pod 'React-jsiexecutor', :path => "#{rn_path}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{rn_path}/ReactCommon/jsinspector"
  pod 'React-jscallinvoker', :path => "#{rn_path}/ReactCommon/jscallinvoker"
  pod 'React-turbomodule-core', :path => "#{rn_path}/ReactCommon/turbomodule/core"
	pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

	pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
	pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
	pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"

 	pod 'react-native-gles', :path => '../../react-native-gles.podspec'

	target 'exampleTests' do
		inherit! :search_paths
	end

  use_native_modules!
end

post_install do |installer|
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.xcconfigs.each do |config_name, config_file|
      config_file.attributes['HEADER_SEARCH_PATHS'] << ' "$(PODS_ROOT)/boost-for-react-native"'
      config_file.attributes['HEADER_SEARCH_PATHS'] << ' "$(PODS_ROOT)/DoubleConversion"'
      config_file.attributes['HEADER_SEARCH_PATHS'] << ' "$(PODS_ROOT)/Folly"'
      config_file.attributes['HEADER_SEARCH_PATHS'] << ' "${PODS_ROOT}/Headers/Private"'
      config_file.attributes['HEADER_SEARCH_PATHS'] << ' "${PODS_ROOT}/Headers/Private/React"'
      config_file.attributes['HEADER_SEARCH_PATHS'] << ' "$(PODS_ROOT)/Headers/Private/React-Core"'
      config_file.attributes['HEADER_SEARCH_PATHS'] << ' "$(PODS_ROOT)/Headers/Private/React-turbomodule-core"'
      config_file.attributes['HEADER_SEARCH_PATHS'] << ' "$(PODS_ROOT)/Headers/Private/React-jscallinvoker"'

      config_file.attributes['OTHER_CFLAGS'] << ' -DFOLLY_NO_CONFIG'
      config_file.attributes['OTHER_CFLAGS'] << ' -DFOLLY_MOBILE=1'
      config_file.attributes['OTHER_CFLAGS'] << ' -DFOLLY_USE_LIBCPP=1'
      config_file.attributes['OTHER_CFLAGS'] << ' -DGLOG_NO_ABBREVIATED_SEVERITIES'

      xcconfig_path = aggregate_target.xcconfig_path(config_name)
      config_file.save_as(xcconfig_path)
    end
  end
end
